// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20250317002159_Seed Data")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("683b171e-34a9-4baf-bb67-e96d3a5a2379"),
                            CreatedOn = new DateTime(2025, 2, 15, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "John Doe",
                            RegistrationDate = new DateTime(2025, 2, 15, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894)
                        },
                        new
                        {
                            Id = new Guid("c2ce3b4f-3290-44bc-a0b0-c8b09e17c4b8"),
                            CreatedOn = new DateTime(2025, 2, 20, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            DateOfBirth = new DateTime(1985, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Alice Smith",
                            RegistrationDate = new DateTime(2025, 2, 20, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894)
                        },
                        new
                        {
                            Id = new Guid("c84ebbc4-22fe-461b-beaf-cab6f0ae9876"),
                            CreatedOn = new DateTime(2025, 2, 25, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            DateOfBirth = new DateTime(1995, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Robert Johnson",
                            RegistrationDate = new DateTime(2025, 2, 25, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894)
                        },
                        new
                        {
                            Id = new Guid("a1d8219b-8b96-4e2f-941b-1a440b1bca37"),
                            CreatedOn = new DateTime(2025, 3, 2, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            DateOfBirth = new DateTime(2000, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Emily Davis",
                            RegistrationDate = new DateTime(2025, 3, 2, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894)
                        },
                        new
                        {
                            Id = new Guid("2e282f47-7d38-47b3-84ec-ad21988ea4d5"),
                            CreatedOn = new DateTime(2025, 3, 7, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            DateOfBirth = new DateTime(1992, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Michael Brown",
                            RegistrationDate = new DateTime(2025, 3, 7, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894)
                        });
                });

            modelBuilder.Entity("Domain.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0edb8354-6bb1-4ab4-b53d-d7a9f6f40aa6"),
                            Article = "ART-001",
                            CreatedOn = new DateTime(2025, 3, 17, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 1",
                            Price = 47m,
                            ProductCategoryId = new Guid("1e4b431b-2866-48c2-9b33-0b69afaec5a8")
                        },
                        new
                        {
                            Id = new Guid("c8a00379-72bd-4b3f-bdc1-33011a301bf2"),
                            Article = "ART-002",
                            CreatedOn = new DateTime(2025, 3, 15, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 2",
                            Price = 870m,
                            ProductCategoryId = new Guid("0173d3c3-d6fe-4faf-aa06-e9075013e3c9")
                        },
                        new
                        {
                            Id = new Guid("a33b8292-81d5-429a-916e-319a82a44f2a"),
                            Article = "ART-003",
                            CreatedOn = new DateTime(2025, 3, 14, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 3",
                            Price = 891m,
                            ProductCategoryId = new Guid("e031aa4c-219f-4acd-a02e-f66d76f9ce90")
                        },
                        new
                        {
                            Id = new Guid("40f93792-881b-4904-a809-12f6ddc3fdeb"),
                            Article = "ART-004",
                            CreatedOn = new DateTime(2025, 3, 12, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 4",
                            Price = 861m,
                            ProductCategoryId = new Guid("6cf7b38f-873d-4a8e-b84f-19c62748dac6")
                        },
                        new
                        {
                            Id = new Guid("284802e7-88a8-4f59-b8ad-c7b0a9c19446"),
                            Article = "ART-005",
                            CreatedOn = new DateTime(2025, 3, 11, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 5",
                            Price = 347m,
                            ProductCategoryId = new Guid("6b7879c0-0b10-42ef-b5e1-ab09ab444a86")
                        },
                        new
                        {
                            Id = new Guid("4883f8e4-fc17-434c-adaf-c5874f6d7064"),
                            Article = "ART-006",
                            CreatedOn = new DateTime(2025, 3, 9, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 6",
                            Price = 680m,
                            ProductCategoryId = new Guid("eaa56e75-60d5-439a-b86b-1f6a50405462")
                        },
                        new
                        {
                            Id = new Guid("d358dbe3-920d-4734-acd7-c6d2059e37b8"),
                            Article = "ART-007",
                            CreatedOn = new DateTime(2025, 3, 8, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 7",
                            Price = 679m,
                            ProductCategoryId = new Guid("eaa56e75-60d5-439a-b86b-1f6a50405462")
                        },
                        new
                        {
                            Id = new Guid("086d0ccc-a574-4127-9acb-ad7df0256f38"),
                            Article = "ART-008",
                            CreatedOn = new DateTime(2025, 3, 6, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 8",
                            Price = 775m,
                            ProductCategoryId = new Guid("e835f150-f353-4661-bbd6-eff22b5b0e86")
                        },
                        new
                        {
                            Id = new Guid("1833123c-160b-49fd-aba4-4e0b766cafbb"),
                            Article = "ART-009",
                            CreatedOn = new DateTime(2025, 3, 5, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 9",
                            Price = 147m,
                            ProductCategoryId = new Guid("e835f150-f353-4661-bbd6-eff22b5b0e86")
                        },
                        new
                        {
                            Id = new Guid("93e28956-aa2d-408c-b9d4-3cae0b5939e1"),
                            Article = "ART-010",
                            CreatedOn = new DateTime(2025, 3, 3, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 10",
                            Price = 397m,
                            ProductCategoryId = new Guid("1e4b431b-2866-48c2-9b33-0b69afaec5a8")
                        },
                        new
                        {
                            Id = new Guid("79f38b24-3c16-4cca-b3bc-e16c8c14e5ed"),
                            Article = "ART-011",
                            CreatedOn = new DateTime(2025, 3, 2, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 11",
                            Price = 576m,
                            ProductCategoryId = new Guid("e835f150-f353-4661-bbd6-eff22b5b0e86")
                        },
                        new
                        {
                            Id = new Guid("417f415b-ce26-4a91-a803-c38aa8d68389"),
                            Article = "ART-012",
                            CreatedOn = new DateTime(2025, 2, 28, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 12",
                            Price = 505m,
                            ProductCategoryId = new Guid("eaa56e75-60d5-439a-b86b-1f6a50405462")
                        },
                        new
                        {
                            Id = new Guid("a86a542c-5185-46d4-916d-896ee753b8d1"),
                            Article = "ART-013",
                            CreatedOn = new DateTime(2025, 2, 27, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 13",
                            Price = 665m,
                            ProductCategoryId = new Guid("ba100768-9308-4bb3-a697-6576675e4063")
                        },
                        new
                        {
                            Id = new Guid("76321a92-1bd3-4131-a86b-7dfe7253da20"),
                            Article = "ART-014",
                            CreatedOn = new DateTime(2025, 2, 25, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 14",
                            Price = 414m,
                            ProductCategoryId = new Guid("6b7879c0-0b10-42ef-b5e1-ab09ab444a86")
                        },
                        new
                        {
                            Id = new Guid("fc415153-2e0c-4d0d-934a-5a985c36dfe4"),
                            Article = "ART-015",
                            CreatedOn = new DateTime(2025, 2, 24, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 15",
                            Price = 709m,
                            ProductCategoryId = new Guid("1e4b431b-2866-48c2-9b33-0b69afaec5a8")
                        },
                        new
                        {
                            Id = new Guid("b71d2aed-e8bf-4d63-a0dd-e692f2541c57"),
                            Article = "ART-016",
                            CreatedOn = new DateTime(2025, 2, 22, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 16",
                            Price = 766m,
                            ProductCategoryId = new Guid("e031aa4c-219f-4acd-a02e-f66d76f9ce90")
                        },
                        new
                        {
                            Id = new Guid("edd592b3-75fd-4590-ae81-27c771771113"),
                            Article = "ART-017",
                            CreatedOn = new DateTime(2025, 2, 21, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 17",
                            Price = 583m,
                            ProductCategoryId = new Guid("6cf7b38f-873d-4a8e-b84f-19c62748dac6")
                        },
                        new
                        {
                            Id = new Guid("8a498516-6265-46f2-816d-86f9c1a16810"),
                            Article = "ART-018",
                            CreatedOn = new DateTime(2025, 2, 19, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 18",
                            Price = 965m,
                            ProductCategoryId = new Guid("5d4857ab-8075-4e78-baad-4ed50531ea57")
                        },
                        new
                        {
                            Id = new Guid("f91a3488-4a14-488c-b1a9-b33af61568a8"),
                            Article = "ART-019",
                            CreatedOn = new DateTime(2025, 2, 18, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 19",
                            Price = 373m,
                            ProductCategoryId = new Guid("e031aa4c-219f-4acd-a02e-f66d76f9ce90")
                        },
                        new
                        {
                            Id = new Guid("529ef17d-4820-4f1e-966f-01a9cd79822b"),
                            Article = "ART-020",
                            CreatedOn = new DateTime(2025, 2, 16, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Product 20",
                            Price = 262m,
                            ProductCategoryId = new Guid("5d4857ab-8075-4e78-baad-4ed50531ea57")
                        });
                });

            modelBuilder.Entity("Domain.Core.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d4857ab-8075-4e78-baad-4ed50531ea57"),
                            CreatedOn = new DateTime(2025, 3, 17, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = new Guid("6b7879c0-0b10-42ef-b5e1-ab09ab444a86"),
                            CreatedOn = new DateTime(2025, 3, 15, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = new Guid("6cf7b38f-873d-4a8e-b84f-19c62748dac6"),
                            CreatedOn = new DateTime(2025, 3, 13, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Category 3"
                        },
                        new
                        {
                            Id = new Guid("eaa56e75-60d5-439a-b86b-1f6a50405462"),
                            CreatedOn = new DateTime(2025, 3, 11, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Category 4"
                        },
                        new
                        {
                            Id = new Guid("ba100768-9308-4bb3-a697-6576675e4063"),
                            CreatedOn = new DateTime(2025, 3, 9, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Category 5"
                        },
                        new
                        {
                            Id = new Guid("78c27bc3-e25b-4133-ae9f-0286edcd39b6"),
                            CreatedOn = new DateTime(2025, 3, 7, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Category 6"
                        },
                        new
                        {
                            Id = new Guid("e835f150-f353-4661-bbd6-eff22b5b0e86"),
                            CreatedOn = new DateTime(2025, 3, 5, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Category 7"
                        },
                        new
                        {
                            Id = new Guid("e031aa4c-219f-4acd-a02e-f66d76f9ce90"),
                            CreatedOn = new DateTime(2025, 3, 3, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Category 8"
                        },
                        new
                        {
                            Id = new Guid("0173d3c3-d6fe-4faf-aa06-e9075013e3c9"),
                            CreatedOn = new DateTime(2025, 3, 1, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Category 9"
                        },
                        new
                        {
                            Id = new Guid("1e4b431b-2866-48c2-9b33-0b69afaec5a8"),
                            CreatedOn = new DateTime(2025, 2, 27, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Category 10"
                        });
                });

            modelBuilder.Entity("Domain.Core.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0f11cf7-37ee-498b-a915-a0e137a52c98"),
                            CreatedOn = new DateTime(2025, 3, 17, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            CustomerId = new Guid("c84ebbc4-22fe-461b-beaf-cab6f0ae9876"),
                            TotalAmount = 1745m
                        },
                        new
                        {
                            Id = new Guid("b57b1484-7040-483a-86ec-54f8cfee048b"),
                            CreatedOn = new DateTime(2025, 3, 15, 19, 33, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("c2ce3b4f-3290-44bc-a0b0-c8b09e17c4b8"),
                            TotalAmount = 52m
                        },
                        new
                        {
                            Id = new Guid("3ec2ee8d-b6ba-47ab-9e5e-7e7113201344"),
                            CreatedOn = new DateTime(2025, 3, 14, 14, 45, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("a1d8219b-8b96-4e2f-941b-1a440b1bca37"),
                            TotalAmount = 1266m
                        },
                        new
                        {
                            Id = new Guid("e543bf0d-9132-4961-a3f9-b4a6e77f7ca0"),
                            CreatedOn = new DateTime(2025, 3, 13, 9, 57, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("2e282f47-7d38-47b3-84ec-ad21988ea4d5"),
                            TotalAmount = 373m
                        },
                        new
                        {
                            Id = new Guid("2a07be41-186e-4283-8a48-9d6032cac3a9"),
                            CreatedOn = new DateTime(2025, 3, 12, 5, 9, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("c84ebbc4-22fe-461b-beaf-cab6f0ae9876"),
                            TotalAmount = 1470m
                        },
                        new
                        {
                            Id = new Guid("94d7925c-d43c-4d65-859d-9424174a0e50"),
                            CreatedOn = new DateTime(2025, 3, 11, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            CustomerId = new Guid("c2ce3b4f-3290-44bc-a0b0-c8b09e17c4b8"),
                            TotalAmount = 519m
                        },
                        new
                        {
                            Id = new Guid("44da26d8-e242-4e2d-9c41-dc8a385f4404"),
                            CreatedOn = new DateTime(2025, 3, 9, 19, 33, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("683b171e-34a9-4baf-bb67-e96d3a5a2379"),
                            TotalAmount = 245m
                        },
                        new
                        {
                            Id = new Guid("1141551d-201b-41af-a57e-772d1d0c0c65"),
                            CreatedOn = new DateTime(2025, 3, 8, 14, 45, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            CustomerId = new Guid("683b171e-34a9-4baf-bb67-e96d3a5a2379"),
                            TotalAmount = 1729m
                        },
                        new
                        {
                            Id = new Guid("010d2413-6993-4930-a79a-a9a2fae8b1f7"),
                            CreatedOn = new DateTime(2025, 3, 7, 9, 57, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("c84ebbc4-22fe-461b-beaf-cab6f0ae9876"),
                            TotalAmount = 138m
                        },
                        new
                        {
                            Id = new Guid("460866b2-b5c9-437b-9d6c-6e7df53e8fc3"),
                            CreatedOn = new DateTime(2025, 3, 6, 5, 9, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("683b171e-34a9-4baf-bb67-e96d3a5a2379"),
                            TotalAmount = 519m
                        },
                        new
                        {
                            Id = new Guid("5c209ffb-a106-4818-9d30-ad14f7ba4d53"),
                            CreatedOn = new DateTime(2025, 3, 5, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            CustomerId = new Guid("2e282f47-7d38-47b3-84ec-ad21988ea4d5"),
                            TotalAmount = 1010m
                        },
                        new
                        {
                            Id = new Guid("5c569ae9-6534-4f0e-8d3c-477f86c0812f"),
                            CreatedOn = new DateTime(2025, 3, 3, 19, 33, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("a1d8219b-8b96-4e2f-941b-1a440b1bca37"),
                            TotalAmount = 1170m
                        },
                        new
                        {
                            Id = new Guid("0667cf5b-b971-4c30-82bf-99aed5286ab7"),
                            CreatedOn = new DateTime(2025, 3, 2, 14, 45, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("a1d8219b-8b96-4e2f-941b-1a440b1bca37"),
                            TotalAmount = 245m
                        },
                        new
                        {
                            Id = new Guid("6e5767d4-68cd-45fd-8eac-19cd1bc19556"),
                            CreatedOn = new DateTime(2025, 3, 1, 9, 57, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("a1d8219b-8b96-4e2f-941b-1a440b1bca37"),
                            TotalAmount = 997m
                        },
                        new
                        {
                            Id = new Guid("51a8c3c3-9b8a-4389-9416-28b472a89c44"),
                            CreatedOn = new DateTime(2025, 2, 28, 5, 9, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            CustomerId = new Guid("a1d8219b-8b96-4e2f-941b-1a440b1bca37"),
                            TotalAmount = 1753m
                        },
                        new
                        {
                            Id = new Guid("c8b96401-871e-4491-9bfd-0629f1075c6c"),
                            CreatedOn = new DateTime(2025, 2, 27, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            CustomerId = new Guid("a1d8219b-8b96-4e2f-941b-1a440b1bca37"),
                            TotalAmount = 1427m
                        },
                        new
                        {
                            Id = new Guid("eee01811-16dd-4551-8fce-37ab808f4ae9"),
                            CreatedOn = new DateTime(2025, 2, 25, 19, 33, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("683b171e-34a9-4baf-bb67-e96d3a5a2379"),
                            TotalAmount = 492m
                        },
                        new
                        {
                            Id = new Guid("0b0346cf-db7a-4f80-ace6-66898b4d789c"),
                            CreatedOn = new DateTime(2025, 2, 24, 14, 45, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("a1d8219b-8b96-4e2f-941b-1a440b1bca37"),
                            TotalAmount = 1922m
                        },
                        new
                        {
                            Id = new Guid("3cb9fa77-8bd6-45c0-94d3-f46da677b4a4"),
                            CreatedOn = new DateTime(2025, 2, 23, 9, 57, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("2e282f47-7d38-47b3-84ec-ad21988ea4d5"),
                            TotalAmount = 257m
                        },
                        new
                        {
                            Id = new Guid("5ef053b8-8c29-4dd2-938b-683b5950a77d"),
                            CreatedOn = new DateTime(2025, 2, 22, 5, 9, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            CustomerId = new Guid("c2ce3b4f-3290-44bc-a0b0-c8b09e17c4b8"),
                            TotalAmount = 1277m
                        },
                        new
                        {
                            Id = new Guid("2aa9087a-9a85-405c-bf48-684e972bcef7"),
                            CreatedOn = new DateTime(2025, 2, 21, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            CustomerId = new Guid("c2ce3b4f-3290-44bc-a0b0-c8b09e17c4b8"),
                            TotalAmount = 998m
                        },
                        new
                        {
                            Id = new Guid("7abbde62-94f0-4655-8d4d-dd1b08c951d1"),
                            CreatedOn = new DateTime(2025, 2, 19, 19, 33, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("683b171e-34a9-4baf-bb67-e96d3a5a2379"),
                            TotalAmount = 1267m
                        },
                        new
                        {
                            Id = new Guid("ef7cc315-71b0-4585-9d01-d4de7b6157b0"),
                            CreatedOn = new DateTime(2025, 2, 18, 14, 45, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("683b171e-34a9-4baf-bb67-e96d3a5a2379"),
                            TotalAmount = 1535m
                        },
                        new
                        {
                            Id = new Guid("2e324283-0466-49c0-ada5-35bcfa7c3e65"),
                            CreatedOn = new DateTime(2025, 2, 17, 9, 57, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("683b171e-34a9-4baf-bb67-e96d3a5a2379"),
                            TotalAmount = 466m
                        },
                        new
                        {
                            Id = new Guid("f6f2d0d5-aa80-4fbd-9446-08045dc7ede9"),
                            CreatedOn = new DateTime(2025, 2, 16, 5, 9, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("2e282f47-7d38-47b3-84ec-ad21988ea4d5"),
                            TotalAmount = 874m
                        },
                        new
                        {
                            Id = new Guid("72e389c0-fedc-4835-a772-bcd3b5e6b6ee"),
                            CreatedOn = new DateTime(2025, 2, 15, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            CustomerId = new Guid("c2ce3b4f-3290-44bc-a0b0-c8b09e17c4b8"),
                            TotalAmount = 1138m
                        },
                        new
                        {
                            Id = new Guid("15f2a50c-440c-42b1-8678-66ceb746dc96"),
                            CreatedOn = new DateTime(2025, 2, 13, 19, 33, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("c84ebbc4-22fe-461b-beaf-cab6f0ae9876"),
                            TotalAmount = 855m
                        },
                        new
                        {
                            Id = new Guid("65f0f6d9-d22c-48e4-964d-841f72f472af"),
                            CreatedOn = new DateTime(2025, 2, 12, 14, 45, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("a1d8219b-8b96-4e2f-941b-1a440b1bca37"),
                            TotalAmount = 214m
                        },
                        new
                        {
                            Id = new Guid("d77ca18b-8bc5-49e6-b0c4-0f50b240aab4"),
                            CreatedOn = new DateTime(2025, 2, 11, 9, 57, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            CustomerId = new Guid("683b171e-34a9-4baf-bb67-e96d3a5a2379"),
                            TotalAmount = 1968m
                        },
                        new
                        {
                            Id = new Guid("6361b982-2196-4111-b586-14b6fc88f484"),
                            CreatedOn = new DateTime(2025, 2, 10, 5, 9, 58, 793, DateTimeKind.Utc).AddTicks(8895),
                            CustomerId = new Guid("a1d8219b-8b96-4e2f-941b-1a440b1bca37"),
                            TotalAmount = 1032m
                        });
                });

            modelBuilder.Entity("Domain.Core.Entities.PurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2eef213-8dc0-48f0-b152-b41e8fa09be5"),
                            CreatedOn = new DateTime(2025, 3, 17, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("0edb8354-6bb1-4ab4-b53d-d7a9f6f40aa6"),
                            PurchaseId = new Guid("f0f11cf7-37ee-498b-a915-a0e137a52c98"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("a10d9030-a905-475b-b65c-e09ef14306cc"),
                            CreatedOn = new DateTime(2025, 3, 16, 21, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("a33b8292-81d5-429a-916e-319a82a44f2a"),
                            PurchaseId = new Guid("f0f11cf7-37ee-498b-a915-a0e137a52c98"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("d2c1149c-7ff3-49be-868b-88fa1a5ad342"),
                            CreatedOn = new DateTime(2025, 3, 16, 18, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("529ef17d-4820-4f1e-966f-01a9cd79822b"),
                            PurchaseId = new Guid("b57b1484-7040-483a-86ec-54f8cfee048b"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("7f26b7ad-f017-41ff-a41b-fc97cdc1f56e"),
                            CreatedOn = new DateTime(2025, 3, 16, 15, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("8a498516-6265-46f2-816d-86f9c1a16810"),
                            PurchaseId = new Guid("b57b1484-7040-483a-86ec-54f8cfee048b"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("f48c9e84-0dc6-4618-bb8d-6997e07f2df4"),
                            CreatedOn = new DateTime(2025, 3, 16, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("fc415153-2e0c-4d0d-934a-5a985c36dfe4"),
                            PurchaseId = new Guid("b57b1484-7040-483a-86ec-54f8cfee048b"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("14af603f-037d-4031-a995-cf1830c3f9ad"),
                            CreatedOn = new DateTime(2025, 3, 16, 9, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("4883f8e4-fc17-434c-adaf-c5874f6d7064"),
                            PurchaseId = new Guid("3ec2ee8d-b6ba-47ab-9e5e-7e7113201344"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("8b14c7b9-4183-44a3-a439-a97be885817e"),
                            CreatedOn = new DateTime(2025, 3, 16, 6, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("b71d2aed-e8bf-4d63-a0dd-e692f2541c57"),
                            PurchaseId = new Guid("3ec2ee8d-b6ba-47ab-9e5e-7e7113201344"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("3ffe6bb9-be49-4f86-ac99-2fcc19ef6cf4"),
                            CreatedOn = new DateTime(2025, 3, 16, 3, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("a86a542c-5185-46d4-916d-896ee753b8d1"),
                            PurchaseId = new Guid("e543bf0d-9132-4961-a3f9-b4a6e77f7ca0"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("9a2c1fdd-448f-4a40-82f6-c7a322d9052a"),
                            CreatedOn = new DateTime(2025, 3, 16, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("086d0ccc-a574-4127-9acb-ad7df0256f38"),
                            PurchaseId = new Guid("e543bf0d-9132-4961-a3f9-b4a6e77f7ca0"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("c13098a1-7a65-4252-b25c-cad4cb454d0c"),
                            CreatedOn = new DateTime(2025, 3, 15, 21, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("a86a542c-5185-46d4-916d-896ee753b8d1"),
                            PurchaseId = new Guid("2a07be41-186e-4283-8a48-9d6032cac3a9"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("6549e886-2042-4490-a94d-32d57440f839"),
                            CreatedOn = new DateTime(2025, 3, 15, 18, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("fc415153-2e0c-4d0d-934a-5a985c36dfe4"),
                            PurchaseId = new Guid("2a07be41-186e-4283-8a48-9d6032cac3a9"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("902aecfc-5051-433a-8bdf-cd55aad468ab"),
                            CreatedOn = new DateTime(2025, 3, 15, 15, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("0edb8354-6bb1-4ab4-b53d-d7a9f6f40aa6"),
                            PurchaseId = new Guid("2a07be41-186e-4283-8a48-9d6032cac3a9"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("d2ea3264-5146-4f2f-a823-2247ba254b3a"),
                            CreatedOn = new DateTime(2025, 3, 15, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("417f415b-ce26-4a91-a803-c38aa8d68389"),
                            PurchaseId = new Guid("94d7925c-d43c-4d65-859d-9424174a0e50"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("51a553f9-776a-4838-8ed1-687bdeba3dd6"),
                            CreatedOn = new DateTime(2025, 3, 15, 9, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("76321a92-1bd3-4131-a86b-7dfe7253da20"),
                            PurchaseId = new Guid("44da26d8-e242-4e2d-9c41-dc8a385f4404"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("9da5aaf0-f750-4db5-86e3-f0cd48eb6191"),
                            CreatedOn = new DateTime(2025, 3, 15, 6, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("fc415153-2e0c-4d0d-934a-5a985c36dfe4"),
                            PurchaseId = new Guid("44da26d8-e242-4e2d-9c41-dc8a385f4404"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("daeb7086-4548-48c0-a11e-b6d79f5377e4"),
                            CreatedOn = new DateTime(2025, 3, 15, 3, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("a86a542c-5185-46d4-916d-896ee753b8d1"),
                            PurchaseId = new Guid("44da26d8-e242-4e2d-9c41-dc8a385f4404"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("04f917a8-d970-4ca5-881f-cc14067982ff"),
                            CreatedOn = new DateTime(2025, 3, 15, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("d358dbe3-920d-4734-acd7-c6d2059e37b8"),
                            PurchaseId = new Guid("1141551d-201b-41af-a57e-772d1d0c0c65"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("630cd9cf-ce25-412e-871e-fb24596f209c"),
                            CreatedOn = new DateTime(2025, 3, 14, 21, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("417f415b-ce26-4a91-a803-c38aa8d68389"),
                            PurchaseId = new Guid("1141551d-201b-41af-a57e-772d1d0c0c65"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("ed28623f-91a9-4209-bc9a-fc16503164a5"),
                            CreatedOn = new DateTime(2025, 3, 14, 18, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("529ef17d-4820-4f1e-966f-01a9cd79822b"),
                            PurchaseId = new Guid("1141551d-201b-41af-a57e-772d1d0c0c65"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("ca23d5cd-e09b-4de7-98f1-e1ca8a648381"),
                            CreatedOn = new DateTime(2025, 3, 14, 15, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("79f38b24-3c16-4cca-b3bc-e16c8c14e5ed"),
                            PurchaseId = new Guid("010d2413-6993-4930-a79a-a9a2fae8b1f7"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("b984e609-84c1-4f40-87d7-3083bd6e6d25"),
                            CreatedOn = new DateTime(2025, 3, 14, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("1833123c-160b-49fd-aba4-4e0b766cafbb"),
                            PurchaseId = new Guid("010d2413-6993-4930-a79a-a9a2fae8b1f7"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("a36ebb73-471c-487f-9411-bf3b87030644"),
                            CreatedOn = new DateTime(2025, 3, 14, 9, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("edd592b3-75fd-4590-ae81-27c771771113"),
                            PurchaseId = new Guid("460866b2-b5c9-437b-9d6c-6e7df53e8fc3"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("698f7b42-121e-463f-aa4c-6f4ce29203ec"),
                            CreatedOn = new DateTime(2025, 3, 14, 6, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("0edb8354-6bb1-4ab4-b53d-d7a9f6f40aa6"),
                            PurchaseId = new Guid("460866b2-b5c9-437b-9d6c-6e7df53e8fc3"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("73a41ad0-ceb3-4f28-89e6-51ce98199880"),
                            CreatedOn = new DateTime(2025, 3, 14, 3, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("f91a3488-4a14-488c-b1a9-b33af61568a8"),
                            PurchaseId = new Guid("5c209ffb-a106-4818-9d30-ad14f7ba4d53"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("51eaf886-6e25-4b4b-a471-0d63d0d20777"),
                            CreatedOn = new DateTime(2025, 3, 14, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("284802e7-88a8-4f59-b8ad-c7b0a9c19446"),
                            PurchaseId = new Guid("5c209ffb-a106-4818-9d30-ad14f7ba4d53"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("036ef20c-2758-48a1-a903-a452295642a4"),
                            CreatedOn = new DateTime(2025, 3, 13, 21, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("529ef17d-4820-4f1e-966f-01a9cd79822b"),
                            PurchaseId = new Guid("5c569ae9-6534-4f0e-8d3c-477f86c0812f"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("f1b5b549-7314-453f-875f-e15e1fe9975e"),
                            CreatedOn = new DateTime(2025, 3, 13, 18, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("284802e7-88a8-4f59-b8ad-c7b0a9c19446"),
                            PurchaseId = new Guid("0667cf5b-b971-4c30-82bf-99aed5286ab7"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("e4f6ba1c-c6a3-45bb-8a3f-62d2592e7251"),
                            CreatedOn = new DateTime(2025, 3, 13, 15, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("edd592b3-75fd-4590-ae81-27c771771113"),
                            PurchaseId = new Guid("0667cf5b-b971-4c30-82bf-99aed5286ab7"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("85a0d0ef-7a39-4e7b-b1f4-23e25f1c65b0"),
                            CreatedOn = new DateTime(2025, 3, 13, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("d358dbe3-920d-4734-acd7-c6d2059e37b8"),
                            PurchaseId = new Guid("0667cf5b-b971-4c30-82bf-99aed5286ab7"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("46a56d59-6a7e-423f-a2c0-3cdb15774f43"),
                            CreatedOn = new DateTime(2025, 3, 13, 9, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("086d0ccc-a574-4127-9acb-ad7df0256f38"),
                            PurchaseId = new Guid("6e5767d4-68cd-45fd-8eac-19cd1bc19556"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("aaf1ffd0-0e09-4229-a4ee-466cabd8ecb2"),
                            CreatedOn = new DateTime(2025, 3, 13, 6, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("4883f8e4-fc17-434c-adaf-c5874f6d7064"),
                            PurchaseId = new Guid("6e5767d4-68cd-45fd-8eac-19cd1bc19556"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("30b7ab69-44f6-4fbc-8e69-4606d562fa11"),
                            CreatedOn = new DateTime(2025, 3, 13, 3, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("d358dbe3-920d-4734-acd7-c6d2059e37b8"),
                            PurchaseId = new Guid("6e5767d4-68cd-45fd-8eac-19cd1bc19556"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("1d7c9e54-6ae2-4fe0-aded-b9545e5a3f41"),
                            CreatedOn = new DateTime(2025, 3, 13, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("4883f8e4-fc17-434c-adaf-c5874f6d7064"),
                            PurchaseId = new Guid("51a8c3c3-9b8a-4389-9416-28b472a89c44"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("1017806a-0312-4170-9320-d596d58c3ee4"),
                            CreatedOn = new DateTime(2025, 3, 12, 21, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("40f93792-881b-4904-a809-12f6ddc3fdeb"),
                            PurchaseId = new Guid("51a8c3c3-9b8a-4389-9416-28b472a89c44"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("3ca93f37-8a97-498c-9aab-b7d4f7ec6efb"),
                            CreatedOn = new DateTime(2025, 3, 12, 18, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("edd592b3-75fd-4590-ae81-27c771771113"),
                            PurchaseId = new Guid("c8b96401-871e-4491-9bfd-0629f1075c6c"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("3b792e60-178b-4888-a3ac-f54738152263"),
                            CreatedOn = new DateTime(2025, 3, 12, 15, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("d358dbe3-920d-4734-acd7-c6d2059e37b8"),
                            PurchaseId = new Guid("c8b96401-871e-4491-9bfd-0629f1075c6c"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("7f92175b-ccc3-493a-848c-4a4800386106"),
                            CreatedOn = new DateTime(2025, 3, 12, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("417f415b-ce26-4a91-a803-c38aa8d68389"),
                            PurchaseId = new Guid("c8b96401-871e-4491-9bfd-0629f1075c6c"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("b66ac84e-b7b3-473c-9268-2e60de03f465"),
                            CreatedOn = new DateTime(2025, 3, 12, 9, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("fc415153-2e0c-4d0d-934a-5a985c36dfe4"),
                            PurchaseId = new Guid("eee01811-16dd-4551-8fce-37ab808f4ae9"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("a1975d50-1cbb-4533-bc5d-36d4d5af3430"),
                            CreatedOn = new DateTime(2025, 3, 12, 6, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("0edb8354-6bb1-4ab4-b53d-d7a9f6f40aa6"),
                            PurchaseId = new Guid("eee01811-16dd-4551-8fce-37ab808f4ae9"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("c094c13b-ca5c-4683-9ded-45b5a113932d"),
                            CreatedOn = new DateTime(2025, 3, 12, 3, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("0edb8354-6bb1-4ab4-b53d-d7a9f6f40aa6"),
                            PurchaseId = new Guid("0b0346cf-db7a-4f80-ace6-66898b4d789c"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("88d82175-7ae8-4b02-9eaf-9dbfd82f4ad9"),
                            CreatedOn = new DateTime(2025, 3, 12, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("a33b8292-81d5-429a-916e-319a82a44f2a"),
                            PurchaseId = new Guid("0b0346cf-db7a-4f80-ace6-66898b4d789c"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("aa55d486-ad0c-40cb-ad3d-7f01e7a6985f"),
                            CreatedOn = new DateTime(2025, 3, 11, 21, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("fc415153-2e0c-4d0d-934a-5a985c36dfe4"),
                            PurchaseId = new Guid("3cb9fa77-8bd6-45c0-94d3-f46da677b4a4"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("fd36486c-6d85-4a36-82a9-222b17417016"),
                            CreatedOn = new DateTime(2025, 3, 11, 18, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("fc415153-2e0c-4d0d-934a-5a985c36dfe4"),
                            PurchaseId = new Guid("3cb9fa77-8bd6-45c0-94d3-f46da677b4a4"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("6058902f-8364-4808-9b22-5e4bd7070792"),
                            CreatedOn = new DateTime(2025, 3, 11, 15, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("529ef17d-4820-4f1e-966f-01a9cd79822b"),
                            PurchaseId = new Guid("5ef053b8-8c29-4dd2-938b-683b5950a77d"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("efedfa60-b01b-4681-91ed-e87f46ecf63a"),
                            CreatedOn = new DateTime(2025, 3, 11, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("edd592b3-75fd-4590-ae81-27c771771113"),
                            PurchaseId = new Guid("5ef053b8-8c29-4dd2-938b-683b5950a77d"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("2a7f8575-a05f-4c29-841e-718f5062d71d"),
                            CreatedOn = new DateTime(2025, 3, 11, 9, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("79f38b24-3c16-4cca-b3bc-e16c8c14e5ed"),
                            PurchaseId = new Guid("2aa9087a-9a85-405c-bf48-684e972bcef7"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("6215245d-8c6a-4874-841f-ffb551d751ff"),
                            CreatedOn = new DateTime(2025, 3, 11, 6, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("0edb8354-6bb1-4ab4-b53d-d7a9f6f40aa6"),
                            PurchaseId = new Guid("7abbde62-94f0-4655-8d4d-dd1b08c951d1"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("8c2727d1-eaf3-4b31-8d98-a118bfd8270a"),
                            CreatedOn = new DateTime(2025, 3, 11, 3, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("40f93792-881b-4904-a809-12f6ddc3fdeb"),
                            PurchaseId = new Guid("7abbde62-94f0-4655-8d4d-dd1b08c951d1"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("b9aafec3-2053-45b8-9b3d-c49d088e50ff"),
                            CreatedOn = new DateTime(2025, 3, 11, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("a86a542c-5185-46d4-916d-896ee753b8d1"),
                            PurchaseId = new Guid("ef7cc315-71b0-4585-9d01-d4de7b6157b0"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("70d61416-8a63-44ac-bd25-831d62eb414b"),
                            CreatedOn = new DateTime(2025, 3, 10, 21, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("40f93792-881b-4904-a809-12f6ddc3fdeb"),
                            PurchaseId = new Guid("2e324283-0466-49c0-ada5-35bcfa7c3e65"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("b14e6669-16eb-46f9-9917-573f444dd5dc"),
                            CreatedOn = new DateTime(2025, 3, 10, 18, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("0edb8354-6bb1-4ab4-b53d-d7a9f6f40aa6"),
                            PurchaseId = new Guid("f6f2d0d5-aa80-4fbd-9446-08045dc7ede9"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("003521ec-eb9f-4b05-9f36-c5ac9cc0ac0e"),
                            CreatedOn = new DateTime(2025, 3, 10, 15, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("284802e7-88a8-4f59-b8ad-c7b0a9c19446"),
                            PurchaseId = new Guid("f6f2d0d5-aa80-4fbd-9446-08045dc7ede9"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("770da579-ab9e-4003-831b-121f49e8d578"),
                            CreatedOn = new DateTime(2025, 3, 10, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("b71d2aed-e8bf-4d63-a0dd-e692f2541c57"),
                            PurchaseId = new Guid("72e389c0-fedc-4835-a772-bcd3b5e6b6ee"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("75e20fee-e464-4ff2-997b-9dbce315a023"),
                            CreatedOn = new DateTime(2025, 3, 10, 9, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("529ef17d-4820-4f1e-966f-01a9cd79822b"),
                            PurchaseId = new Guid("72e389c0-fedc-4835-a772-bcd3b5e6b6ee"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("a0d67b99-6226-47c5-9f52-f8b7365b3fc7"),
                            CreatedOn = new DateTime(2025, 3, 10, 6, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("086d0ccc-a574-4127-9acb-ad7df0256f38"),
                            PurchaseId = new Guid("15f2a50c-440c-42b1-8678-66ceb746dc96"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("0c5b1384-45d9-47f1-8fd9-734bb6a09eec"),
                            CreatedOn = new DateTime(2025, 3, 10, 3, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("529ef17d-4820-4f1e-966f-01a9cd79822b"),
                            PurchaseId = new Guid("65f0f6d9-d22c-48e4-964d-841f72f472af"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("d3ce2a7d-79c6-4592-ba8b-bbff676eb54c"),
                            CreatedOn = new DateTime(2025, 3, 10, 0, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("76321a92-1bd3-4131-a86b-7dfe7253da20"),
                            PurchaseId = new Guid("65f0f6d9-d22c-48e4-964d-841f72f472af"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("a904613d-9fe2-4283-afbf-b070d10b6c25"),
                            CreatedOn = new DateTime(2025, 3, 9, 21, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("8a498516-6265-46f2-816d-86f9c1a16810"),
                            PurchaseId = new Guid("d77ca18b-8bc5-49e6-b0c4-0f50b240aab4"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("677134a7-9da0-4289-baf3-cb1b2c4e599a"),
                            CreatedOn = new DateTime(2025, 3, 9, 18, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("a86a542c-5185-46d4-916d-896ee753b8d1"),
                            PurchaseId = new Guid("d77ca18b-8bc5-49e6-b0c4-0f50b240aab4"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("a07f2a53-9841-454c-a335-1ad5f38546ac"),
                            CreatedOn = new DateTime(2025, 3, 9, 15, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("529ef17d-4820-4f1e-966f-01a9cd79822b"),
                            PurchaseId = new Guid("d77ca18b-8bc5-49e6-b0c4-0f50b240aab4"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("f90a7535-5647-4c00-8756-3ca13adb2f8b"),
                            CreatedOn = new DateTime(2025, 3, 9, 12, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("93e28956-aa2d-408c-b9d4-3cae0b5939e1"),
                            PurchaseId = new Guid("6361b982-2196-4111-b586-14b6fc88f484"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("bec3204a-c0d6-4b68-92ef-99124d14eff0"),
                            CreatedOn = new DateTime(2025, 3, 9, 9, 21, 58, 793, DateTimeKind.Utc).AddTicks(8894),
                            ProductId = new Guid("c8a00379-72bd-4b3f-bdc1-33011a301bf2"),
                            PurchaseId = new Guid("6361b982-2196-4111-b586-14b6fc88f484"),
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Domain.Core.Entities.Product", b =>
                {
                    b.HasOne("Domain.Core.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Domain.Core.Entities.Purchase", b =>
                {
                    b.HasOne("Domain.Core.Entities.Customer", "Customer")
                        .WithMany("Purchases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Core.Entities.PurchaseItem", b =>
                {
                    b.HasOne("Domain.Core.Entities.Product", "Product")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Core.Entities.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Domain.Core.Entities.Customer", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Domain.Core.Entities.Product", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("Domain.Core.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Core.Entities.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });
#pragma warning restore 612, 618
        }
    }
}
